version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      COURSES_URL: '192.168.99.101'
      COURSES_PORT: '4000'
      COURSES_ENTRY: 'courses'
      TEACHERS_URL: '192.168.99.101'
      TEACHERS_PORT: '4000'
      TEACHERS_ENTRY: 'teachers'
      RESOURCES_URL: '192.168.99.101'
      RESOURCES_PORT: '4000'
      RESOURCES_ENTRY: 'resources'
      COMMENTS_URL: 'localhost'
      COMMENTS_PORT: '8000'
      COMMENTS_ENTRY: 'comments'
    ports:
      - '5000:5000'