version: '3'

services:
  django_db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  django_web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code
    ports:
      - "8000:8000"
    depends_on:
      - django_db
