version: '3'

services:
  comments-db:
    image: postgres
  comments-ms:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code
    ports:
      - "8000:8000"
    depends_on:
      - comments-db
