version: '3'
services:
  resources-db:
    image: postgres
  resources-ms:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - ./myapp
    ports:
      - "4000:4000"
    depends_on:
      - resources-db

