version: "3"
services:
  users-ms:
    build: ./users-restapi
    networks:
      - mongo-go
      - nginx-go
    ports: 
      - 3000:3000
    depends_on:
      - users-db
    
  users-nginx:
    image: itwars/nginx-http2
    volumes: 
            - /home/vrh/docker/myrepo/stack-mongo-golang-vuejs-nginx/nginx-http2/conf/:/etc/nginx/conf.d/
    ports:
            - 80:80
            - 443:443
    networks: 
            - nginx-go
    depends_on:
      - users-ms
   
  users-db:
    image: itwars/mongodb
    volumes:
            - mongodb-data:/data/db
    networks:
      - mongo-go
    ports:
            - 28017:28017
    
networks:
  mongo-go:
  nginx-go:
volumes:
  mongodb-data:
