version: "3"
services:
  users-ms:
    build: ./users-restapi
    ports: 
      - 3000:3000
    depends_on:
      - users-db
  users-db:
    image: mongo
    volumes:
       - /data/mongodb1/db:/data/db
    ports:
       - 28017:28017
